import './globals.css'
import Navbar from '../components/navbar.js'
import Footer from '../components/footer.js'

export const metadata = {
  title: 'CIBS - Cambridge Investment Banking Society',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  	return (
    <html lang="en">
      	<body>
			<Navbar />
			{children}
			<Footer />
		</body>
    </html>
  	)
}
