import './globals.css'
import { EB_Garamond } from 'next/font/google'
import Navbar from '../components/navbar.js'
import Footer from '../components/footer.js'

const inter = EB_Garamond({ subsets: ['latin'] })

export const metadata = {
  title: 'CIBS - Cambridge Investment Banking Society',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  	return (
    <html lang="en">
      	<body className={inter.className}>
			<Navbar />
			{children}
			<Footer />
		</body>
    </html>
  	)
}
